### ISSUE TITLE
Scripts & Windows 10

### ISSUE THREAD

**Issue by lisaholker** [MN-Script-Team/DHS-MAXIS-Scripts#2977] opened 2017-10-11 19:25 UTC
We're doing testing with Windows 10 in our county & have figured out that Scripts don't work with them.  Our IT department said they have contacted "the state" about getting this issue resolved but I'm wondering if anyone on here is aware of this issue & have any more info on timelines of scripts working with Windows 10. 

Thanks!!

**Comment by Farleight** [comment] 2017-10-11 19:34
It is known, and has been the subject of much recent testing. Pinpointing the exact cause has proven to be difficult, but very smart people are dedicating time to figuring out a solution... and actually just earlier today, an extra very smart person just indicated that she's about to take up the cause as well... so send good vibes. The A-Team is on it.

**Comment by lisaholker** [comment] 2017-10-11 19:35
Yay!! So excellent to hear, thank you!

Lisa Holker
Financial Assistance Supervisor
Sherburne County Health & Human Services
13880 Business Center Dr.
Elk River, Mn. 55330
Phone: 763-765-4021 Fax: 763-765-4096
Sherburne County Health and Human Services values customer service and would like to hear from those who receive services from us about your most recent experience.  Please visit this link https://www.surveymonkey.com/r/SCHHS2015 to complete a quick survey.  Your assistance in completing this will help us improve internal efficiencies and the quality of services to Sherburne County residents.
Please disregard if you have already completed a survey in the last 90 days.  Thank you.

The information contained in this email is confidential information intended only the use of the individual or entity named above.  If the reader of this message is not the intended recipient, or the employee or agent responsible to deliver to the intended recipient, you are hereby notified that any dissemination or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify us by responding directly to this email and destroy all information received immediately.

**Comment by WCMattAnderson** [comment] 2018-02-10 01:50
See https://github.com/MN-Script-Team/DHS-PRISM-Scripts/issues/797 for resolution. Need to update to 7.1.5 BlueZone version.

**Comment by C-Love** [comment] 2018-02-21 18:25
Since there is a solution for this and has been listed, we will close this issue.

**Closed by C-Love** 2018-02-21 18:25 UTC
