### ISSUE TITLE
CAF addendum

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#577] opened 2015-04-20 16:28 UTC
With all this talk about possible CAF script upating, how about a CAF addendum option.  Or just a new script all together?

**Comment by theVKC** [comment] 2015-04-20 16:40
This is a duplicate of #89... if you want it, comment on that particular issue, @IlseFerris! :8ball:

**Closed by theVKC** 2015-04-20 16:40 UTC

**Comment by IlseFerris** [comment] 2015-04-20 16:58
Well then, that will teach me to search before posting.  I'm totally failing at Mondays today.
