### ISSUE TITLE
EDRS Case Note Needed

### ISSUE THREAD

**Issue by ramonalisa1** [MN-Script-Team/DHS-MAXIS-Scripts#315] opened 2015-01-12 15:02 UTC
I see a need for a new NOTE - EDRS based on the below:

The Electronic Disqualified Recipient System (eDRS) is an exchange of Federal Supplemental Nutrition Assistance Program (SNAP) clients who have been charged with a fraud disqualification.  Since the SNAP program is a federal program, offenses charged in one state are in effect in all other states as well.

 

Effective 01/13/15, for all new SNAP applications, as well as recertification’s,  check to see if a SNAP recipient is currently serving a disqualification in another state.  Navigate to INFC/EDRS.  Enter the SSN of the SNAP member.  If no match is found, complete a search using the member’s First and Last Name.  If no match is found, approve SNAP.  If a match is found, contact information for the State in which the recipient is disqualified will be provided.  

Contact the State following policy instructions in TE02.08.127 SNAP ELECTRONIC DISQUALIFIED RECIPIENT SYSTEM.

 

The MAXIS DISQ panel has been updated to reflect some changes needed in order to implement the new eDRS process:

 

1)    FS Types 01,21,22, and 24 will expire effective 01/13/15 in the benefit month of 01/2015.  Types 02, 03, and 04 will still be available to use for SNAP Fraud Disqualifications.  If an old MAXIS panel exists with type 01,21,22, or 24 that needs to be updated, the Type will need to be changed to 02, 03, or 04.  If a DISQ panel with type 01,02,03,04,22,22, or 24 needs to be deleted, contact the TSS Help Desk for assistance.

 

2)    2 new fields, ‘SNAP Trafficking (Y/N): _” and “SNAP Offense Description: __” have been added to the DISQ panel.  Fraud Investigators will indicate 

to MAXIS workers which code to enter on each field.  

 

CM section 0025.24.08 SNAP ELECTRONIC DISQUALIFIED RECIPIENT SYSTEM and POLI/TEMP section TE02.08.127 SNAP eDRS  will be updated in the near future to reflect this change.

**Comment by CDPotter** [comment] 2015-01-12 16:16
Robert and I were planning to take a look at it but the screen isn't available to us yet so we can't start anything quite yet.

**Comment by theVKC** [comment] 2015-01-12 18:04
Closing issue as duplicate of #271. @ramonalisa1, before submitting a new issue, you should probably do a quick search to see if it's already been reported. :)

**Closed by theVKC** 2015-01-12 18:04 UTC
Labels: duplicate
