### ISSUE TITLE
MA-EPD Fiater

### ISSUE THREAD

**Issue by ValAnderson** [MN-Script-Team/DHS-MAXIS-Scripts#3009] opened 2018-02-07 14:50 UTC
User reported an error "Type Mistmatch: 'income_job_01". It appears the location referenced in the script is to read 8, 11, 63 and that it should be 8, 12, 67 on the STAT/JOBS panel.

**Comment by Farleight** [comment] 2018-02-07 15:01
The 11, 63 coordinate is in reference to the HC Est pop-up window. That should be correct. There is some logic written in there that may or may not switch the coordinate where it places the X to transmit into the pop-up window in the first place... I have not gone down that rabbit hole yet to see if your issue might be there, but I'm guessing someone else probably knows more about it... so hopefully you'll have another response long before I have time to investigate further. Stay tuned!

**Comment by C-Love** [comment] 2018-02-12 18:32
I would guess this is actually an issue of the script attempting to do math with a string or a blank variable. A type_mismatch wouldn't be called from just reading the data. And @Farleight is correct - the coordinates seem to be accurate. I am guessing the issue is actually being called when the script his line 270.

**Comment by C-Love** [comment] 2018-02-21 18:38
@ValAnderson - is this issue continuing? Do you have other reports of this error? We have had no other reports. This may be user error in that no HC Income Estimate was listed in a case.

**Comment by ValAnderson** [comment] 2018-02-26 21:17
I haven't received any other reports of this error.

**Comment by C-Love** [comment] 2018-02-27 20:03
Closing as this has not been repeated - will reopen if more reports come in.

**Closed by C-Love** 2018-02-27 20:03 UTC
Labels: Category: ACTIONS, Type: bug, question
