### ISSUE TITLE
Critical Bug -- NOTES - Approved Progs DWP/MFIP transition

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1593] opened 2016-01-06 16:57 UTC
I feel like we've talked about this (maybe it was for Krabappel), but today, a worker reported that Approved Progs was not working on his DWP/MFIP transition case. 

When the script goes to ELIG/SUMM, it finds a version of both DWP and MFIP and goes off to check both programs for that month. When the script tries to get into ELIG/DWP, MAXIS pops up a warning message "This version of DWP was auto-closed on DD/MM/YY for Four Month Eligibility Limit."

I have a fix ready in the hopper. We have tested it with the worker that reported the bug and it worked.

**Comment by theVKC** [comment] 2016-01-07 15:58
Duplicate of #1262

**Closed by theVKC** 2016-01-07 15:58 UTC
Labels: bug, duplicate, NOTES scripts
