### ISSUE TITLE
LTC - 5181 Bug

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#643] opened 2015-05-29 15:19 UTC
When clicking next on the 1st dialog, it pops up the "Are you sure you want to exit" msgbox, if you select no it jumps into stat and starts trying to update panels?

**Comment by CDPotter** [comment] 2015-05-29 15:23
I can confirm that this issue is happening in Anoka as well. I'm trying to take a look at it today but it's slow going since it's the last day of the month/my intake day. 

If someone wants to take a crack at it, it looks to be something with the logic on the do loops, for something with a working structure someone might be able to use the CAF as an example for a complicated dialog loop like this.

**Comment by theVKC** [comment] 2015-05-29 16:25
Resolved with #644

**Comment by CDPotter** [comment] 2015-05-29 16:28
Well... that's bizarre when I run it locally the next button worked but when I run the newly uploaded one it doesn't work (but at least it doesn't nav into panels anymore if you hit no on the cancel dialog.)

**Comment by theVKC** [comment] 2015-05-31 15:48
Not resolved. @IlseFerris and I are sitting in Dunn Bros. and we're going to take this out.

**Closed** 2015-05-31 15:55 UTC
Labels: bug, NOTES scripts

**Comment by theVKC** [comment] 2015-05-31 16:22
Nice catch on the DIM'd variables, @IlseFerris. I would not have looked at this as an issue right away.
