### ISSUE TITLE
Power Pad Button Not Working

### ISSUE THREAD

**Issue by ramonalisa1** [MN-Script-Team/DHS-MAXIS-Scripts#387] opened 2015-02-06 21:30 UTC
Workers are reporting the Power Pad button for Notes H - Z is not working.  All other buttons are working.

**Comment by CDPotter** [comment] 2015-02-06 21:34
Seems to be working here at Anoka. Might the workers have another script open elsewhere? I've noticed every now and then a menu won't open and it remains "playing" for a while. I've just been hitting stop script to get around it.

**Comment by ramonalisa1** [comment] 2015-02-06 21:41
Nope, that's not the issue.  It is all of us and I tried mine twice.  I have checked and all the others work fine, just not that one.  Hmmmmmm....

**Comment by ramonalisa1** [comment] 2015-02-06 21:45
Ran the installer again and everyone is working again.  Weird!!

**Comment by lpshanley** [comment] 2015-02-06 22:07
Problem solved, crisis averted!

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by theVKC** [comment] 2015-02-08 01:25
In the weird event that a Power Pad button doesn't work, you can sort-of tell what the issue is by the circumstances surrounding it.

* If it "doesn't work" for just one user, and no buttons work, it's likely they're running another script somewhere. Close that script and it'll work (or just restart BlueZone, that usually does it).
* If it throws a "something is wrong" error, or an error with a really long seemingly random string of numbers as soon as you hit the button, it might be a GitHub error. Those could be epic if they happen to everyone, it implies our connection to the server was lost. So far, I've only seen that when I change the name of a repository, and even then it's only temporary.
* If the one button just "doesn't work", but the others do, it's likely something was corrupted on your share drive. Tip: keep the scripts in a read-only directory for most users. Rebuilding the script (i.e. run the installer again) can fix it, but it doesn't always work.

Closing issue, since it seems like it's been resolved.

**Closed by theVKC** 2015-02-08 01:25 UTC
