### ISSUE TITLE
CAF check if WREG exists for a minor child, throw error instead of script breaking

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#1261] opened 2015-10-13 18:29 UTC
I am not sure if this is something we want to write into the script or not. It is a bit of an oddity. 
Some workers add WREG panels for children under the age of 16 - they then code it with '06 - Under Age 16' in the FSET Status and leave ABAWD Status blank. I have been told this is acceptable. (No idea why anyone would want to add WREG panels for children). The NOTES - CAF script Errors out when it tries to read those panels (just like I do...).

The question is, should we add functionality to essentially ignore these (not sure how this would work or if it is possible) or should this just be something that workers need to adjust their process on?

**Comment by CDPotter** [comment] 2015-10-14 13:42
Typically when @RobertFewins-Kalb and I have run into these we've been telling people to just update the ABAWD code. I'm fairly sure that if you pf9 on the panel you will get an edit stating ABAWD code is missing and you can't save it until you code it as such. I think our logic for not fixing it was it brought attention to the incorrectly coded ones. We had issues with workers just pf10ing to get past edits when they should have been updating the ABAWD code.

**Comment by theVKC** [comment] 2015-10-15 18:10
My vote would be to program the script to error out _with additional info to inform the worker._ Any thoughts? @ruthmaloney, have anything to say?

**Comment by ruthmaloney** [comment] 2015-10-27 18:19
I also don’t understand why a worker would add a WREG panel for a minor unless it prompts some sort of DAIL when the kid turns 16? I have no idea if MAXIS does that. I agree that if the workers are putting the panel in, the script should have an error message to fix it, not to ignore it – preferably delete it – I’m an advocate for no unnecessary panels. I’m pretty sure MAXIS will give an edit message to add a WREG panel for anyone 16+ if it doesn’t exist, so no need to have it in there early.

Ruth Maloney

**Comment by RobertFewins-Kalb** [comment] 2015-10-27 18:23
It's not about blank WREG panels, the problem is when there is a WREG panel but no ABAWD status. We can't fathom why it would be allowed (other than it being a panel that was created at a time when ABAWD status wasn't a mandatory field). There is no inhibiting edit when the member is active on FS, is older than 16, but doesn't have an ABAWD status.

**Comment by ruthmaloney** [comment] 2015-10-27 18:35
If the script ignores it and MAXIS isn’t programed to produce an inhibiting edit, there will be additional errors as those children change to ABAWD age (assuming the case stays open and the worker continues using scripts). If the script continues to error out, the workers are forced to update the WREG panel or delete it if it’s unnecessarily in there, right?

Ruth Maloney

**Comment by theVKC** [comment] 2015-10-28 20:10
@RobertFewins-Kalb, it kind of sounds like this gets to the heart of a few different issues we may be running into about philosophy of telling workers info vs. suggesting info. What do you think?

I propose we summit about this, and Project Gorbachev, Thursday, at Anoka.

**Comment by RobertFewins-Kalb** [comment] 2015-10-28 20:14
Nayeth, Right Honourable @theVKC , for you see, I shall be leading a child support training in Dakota County, Thursday.

**Comment by RobertFewins-Kalb** [comment] 2015-10-28 20:16
To your first question, however, I prefer that the script error out in this situation to do what Maxis _should_ be doing. That was how we first became aware of the issues with the ABAWD status. And, lo, tho tradition ought naught dictate the future, I like letting the script error out as a way of holding a torch under bottoms.

**Comment by RobertFewins-Kalb** [comment] 2015-10-28 20:17
(I have no idea where this is coming from.)

**Comment by theVKC** [comment] 2015-10-28 20:31
I think it should error out too, but it should error out with a message saying why it errored out. Does that make sense?

**Comment by RobertFewins-Kalb** [comment] 2015-10-28 20:36
Instead of a run time error. It makes perfect sense! Love it.

**Comment by theVKC** [comment] 2015-10-28 20:49
Great! Now, can you build it, @RobertFewins-Kalb? That's my million dollar question.

**Comment by RobertFewins-Kalb** [comment] 2015-10-28 21:04
of course

**Comment by RobertFewins-Kalb** [comment] 2015-10-28 21:05
million dollars, please

**Comment by theVKC** [comment] 2015-12-30 21:49
@RobertFewins-Kalb, can I get an update on this?

**Comment by RobertFewins-Kalb** [comment] 2015-12-31 15:06
none progress

**Comment by theVKC** [comment] 2016-01-11 19:18
@MelissaFox-Stearns wants it!

**Comment by RobertFewins-Kalb** [comment] 2016-01-11 19:23
do it to it

**Comment by MelissaFox-Stearns** [comment] 2016-01-11 19:43
So...I'm not even able to put in a Wreg panel for a minor child without also putting in an ABAWD status. Has anyone had success faking this? Or does anyone have a real case I can reference?

**Comment by RobertFewins-Kalb** [comment] 2016-01-11 19:47
Sorry. Finding one has been a total crap shoot. You'll have to find one in Production or Inquiry because WREG has been updated since 2013 to create an inhibiting edit wherein you cannot create or edit a WREG panel with FS = "Y" and ABAWD Status = "__".

**Comment by RobertFewins-Kalb** [comment] 2016-01-11 19:54
I might have a way of getting one for you. Standby...

**Comment by MelissaFox-Stearns** [comment] 2016-01-11 20:04
Sounds good Robert. I'm confused how the script can even break because the function "call autofill_editbox_from_MAXIS" has this:
If read_abawd_status = "__" THEN  abawd_status = "ABAWD = blank"

So it looks like it's already looking for a blank ABAWD. I mean I suppose the worker should still be notified that it needs updating but are we sure this is still causing problems?

**Comment by theVKC** [comment] 2016-01-11 20:38
I'm not convinced this is worth working on. @RobertFewins-Kalb: last dibs on doing it (otherwise I'm planning on closing the issue).

**Comment by CDPotter** [comment] 2016-01-11 20:39
Robert and I are (just checked with him) fine with leaving it the way it is. The script error will bring attention to it.

**Comment by theVKC** [comment] 2016-01-11 20:42
Agreed. Thanks all!

**Closed by theVKC** 2016-01-11 20:42 UTC
Labels: enhancement, NOTES scripts

**Comment by RobertFewins-Kalb** [comment] 2016-01-11 20:52
Update: I finally found a case, single adult, FS only, FSET Status = 16 (age 50-59), ABAWD Status = __. Panel update date = 03/26/2014. No error... Glad this is closed because I am more confused.
