### ISSUE TITLE
CAF (NOTES #-G) ~ Add field to explain what EI was used/how EI was calculated

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#369] opened 2015-01-30 21:55 UTC
Per worker/supervisor suggestion: It would be helpful if there was a box right below EI to list how we calculated EI. Since for food they want us to case/note what income was used/how it was calculated. I don't see that people are case/noting this at all. Workers are just using what the script says "PIC is 300/biweekly" but nothing on what income was used to get to the $300. Suggestion is to have a separate field specifically listing what income was used to prevent that info from being missed.

**Comment by CDPotter** [comment] 2015-01-30 21:58
There is already a field below EI called "notes on income and budget" where we at Anoka instruct workers to be more detailed about how things are budgeted.

**Comment by theVKC** [comment] 2015-02-01 19:57
It might be worthwhile to consider splitting that out, though. Mainly because our reviewers are being so explicit with wanting this information. I'm even contemplating making it mandatory if there's any income entered into the case note at all.

**Comment by courtrightd** [comment] 2015-02-02 14:06
I think making it a mandatory field (if income) would be an excellent idea.

**Comment by theVKC** [comment] 2015-06-08 18:55
Closed for lack of interest, it's also somewhat a duplicate of #370.

**Closed by theVKC** 2015-06-08 18:55 UTC
Labels: enhancement, NOTES scripts
