### ISSUE TITLE
NOTES/Good Cause Results ~ Error message (can't open case note. are you in inquiry?)

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#2059] opened 2016-03-30 22:16 UTC
The supervisor that handles our Good Cause cases received an error while she attempted to run the Good Cause Results script. She selected Denied; filled in the information; and clicked on OK. Once she did that, she received an error that said "The script can't open a case note. Are you in inquiry? Check MAXIS and try again". She was in S1 production. Also, when she clicked on Ok on the message box, the message would not go away. She had to click on Stop Script in order for it to go away. Let me know if you need further details. Screen shot of error is attached.
![bz script good cause results error message](https://cloud.githubusercontent.com/assets/10159901/14159363/17c1aeae-f69b-11e5-8fc5-719b957bafec.JPG)

**Comment by theVKC** [comment] 2016-03-31 16:21
@ALJ10: any chance this is a fluke? Sometimes MAXIS just needs a good restart when this pops up.

In any case, if you get this a lot, consider closing and reopening your inquiry window.

I'm going to close this since it doesn't sound like a script issue, but more of a BlueZone/connectivity issue.

**Closed by theVKC** 2016-03-31 16:21 UTC
Labels: wontfix

**Comment by JonesPat** [comment] 2016-04-20 14:21
We are having reports of this same issue at Dakota County. Verified session as well and it is correct.

**Comment by IlseFerris** [comment] 2016-04-20 14:32
Confirmed as an issue. I'll submit a fix.

**Comment by theVKC** [comment] 2016-04-20 14:33
@IlseFerris, since this is a closed issue, please provide a reason it's been confirmed as an issue before we reopen this.

**Comment by IlseFerris** [comment] 2016-04-20 14:44
OK, so I was able to replicate the issue once, but not since. The script wasn't able to move past the SELF menu screen using CALL start_a_blank_case_note. Could have been a connection issue. I was able to stopscript, and run it again. 

This can stay closed.

**Comment by theVKC** [comment] 2016-04-20 14:51
Users should check their API settings in Settings>API to see if it matches the settings indicated in "How to Install BlueZone Scripts". If inquiry and production are getting cris-crossed, this is often the reason. Again, not a script issue, but a BlueZone settings issue.

**Comment by RobertFewins-Kalb** [comment] 2016-04-20 14:54
I just tried the script and it did the same thing for me that @IlseFerris is talking about.

Another problem, when I hit the OK button, it asks if I want to cancel.

**Comment by RobertFewins-Kalb** [comment] 2016-04-20 15:02
It appears to be malfunctioning only from SELF. When the script is run from inside a case, it works. I'm thinking the problem might have to do with the script not writing the case number anywhere.

Also, my _worker_signature_ is not auto-filling.

**Comment by IlseFerris** [comment] 2016-04-20 15:17
I've been testing it from SELF, CASE/NOTE and STAT without issue for the last 10 minutes. @RobertFewins-Kalb are you still running into issues?

**Comment by RobertFewins-Kalb** [comment] 2016-04-20 15:21
I still get the _cancel_confirmation_ msgbox when I press OK.

I was able to force it through. When I get the warning about not being in production, I navigate to CASE/NOTE for the case (because it's still not entering the case number from SELF) and then it works.

I've also noticed that the script uses _case_number_ instead of _maxis_case_number_.

**Comment by courtrightd** [comment] 2016-04-20 15:28
I noticed this exact behavior with using subroutines for chainloading, because it messes up the variable scope.  Any chance it has to do with the Dimming of variables in this one?

**Comment by IlseFerris** [comment] 2016-04-20 15:32
I think you're right @courtrightd

**Comment by IlseFerris** [comment] 2016-04-20 15:54
The case number variables are also not identical. Some are Case_Number and some are case_number. I think this issue should be reopened. It can be assigned to me.

**Comment by theVKC** [comment] 2016-04-20 16:51
OK, there's a lot going on here! Was this script tested? Seems we should have caught this stuff.

I don't know how `Case_Number` could be behaving differently from `case_number`.

https://blogs.technet.microsoft.com/heyscriptingguy/2005/06/22/how-can-i-compare-two-string-values-regardless-of-letter-case/

In any case, I will reopen the issue only if @IlseFerris (or someone else) can find and demonstrate the specific bug that's involved. If it was working with Ilse sometimes and not other times I'm hesitant to open a ghost issue.

**Comment by IlseFerris** [comment] 2016-04-21 16:10
I won't be able to work on this in the next few working days. If anyone else is willing, that would be amazing.

**Comment by ALJ10** [comment] 2016-05-12 19:32
Just a follow up that we're still experiencing the issues with this script. I had the supervisor try the workarounds that were mentioned the above comments, but to no avail. Let me know if there's anything else we can try until the script issue has been resolved. Thank you!

**Comment by theVKC** [comment] 2016-05-12 19:33
You aren't on the master branch so you won't see the fix until the release date Monday after next.

**Comment by theVKC** [comment] 2016-05-12 19:38
Updated comment: nobody has been able to demonstrate an actual bug with this script. That pop up is supposed to show up when you're in inquiry and it's not duplicatable otherwise.

I recommend your supervisor reinstall BlueZone, and ensure api settings are correct for this user. There is no other reason we can see that would explain this issue.

**Comment by theVKC** [comment] 2016-05-12 19:40
In any case I renamed the variables yesterday, so if dim ing was responsible that should resolve it next release.
