### ISSUE TITLE
Error on Agency Custom Button

### ISSUE THREAD

**Issue by ramonalisa1** [MN-Script-Team/DHS-MAXIS-Scripts#412] opened 2015-02-24 14:49 UTC
When using the new script to navigate betweenf olders, I am getting the following error:  "Dialog ID 212 is Out of Range".

**Comment by lpshanley** [comment] 2015-02-24 14:57
It seems that only certain people are getting these errors. Is everyone having this error?

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by lpshanley** [comment] 2015-02-24 15:04
I pushed a fix to help me debug the problem to git. When V merges this then I will be able to know more.

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by theVKC** [comment] 2015-02-24 15:05
Could it be possible that the issue has to do with the script itself and not the new feature? Was it working before in Agency Custom? That error typically means that a dialog named a certain thing (such as “CEI_dialog”) doesn’t exist.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by lpshanley** [comment] 2015-02-24 15:28
The issue is odd because its working without any issue for some people and its getting the out of range for some people.

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by theVKC** [comment] 2015-02-24 16:18
@ramonalisa1, can you tell us if the issue is happening with multiple users, and, was this script used in the old version of the Agency Custom script?

**Comment by lpshanley** [comment] 2015-02-24 17:39
I am submitting the changes and updates from my own repo just as a heads up. I just sent another commit with a pretty significant update. Essentially I am forcing to script to ReDim every array every time it reuses it. Technically speaking this means the array now should not be possible to be out of range as every time its used the range is redefined. This change seems to have corrected all of our issues in SLC at the moment. We are currently using a local copy and its running stable. All the users that were having issues seems to be working like a charm. We are having a goofy issue only when running from git raw however I’m unsure if its raw or if it is how we did the redirect that causes the issue. I would like to see if merging the changes now would correct peoples issues. Nothing from the new build will cause any more issues than currently exist so really it’s a win win ☺

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by lpshanley** [comment] 2015-02-24 20:07
Are you still getting the same error now?

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by ramonalisa1** [comment] 2015-02-24 20:15
Yep.  Still getting the same error.

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by lpshanley** [comment] 2015-02-24 20:19
Is it everyone or only select people?

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by ramonalisa1** [comment] 2015-02-24 20:31
Select.  Some people get the error, some get a blank message box, and some can use it fine.

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by theVKC** [comment] 2015-02-24 20:39
I just pull requested @lpshanley’s newest fix into beta. @ramonalisa1, can you tell us if it’s better now?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by ramonalisa1** [comment] 2015-02-24 21:00
Nope, still getting error:

[cid:image001.png@01D05042.95F06E10]

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by theVKC** [comment] 2015-02-24 21:02
OK, I might have missed this earlier, but can you confirm for me that you had this script in the Agency Custom folder before yesterday’s update, and it worked then, but doesn’t now?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by ramonalisa1** [comment] 2015-02-24 21:10
Correct.  I have used it before, but when I tried it after yesterday’s update, the error message started.

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by theVKC** [comment] 2015-02-24 21:44
Do other users experience it too? Or is it just you? Trying to isolate whether-or-not we merely have a branch identity/URL issue.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by courtrightd** [comment] 2015-02-24 21:47
In SLC it occurs with some users, 50% of the ones I checked.  It occurred only after the Beta update and is definitely related to that change.  It occurs when I change the redirect to point to Lucas’s repository or the beta repository.  There is no issue if I replace the redirect with the actual script file in the local directory.

**Comment by ramonalisa1** [comment] 2015-02-24 21:49
Some users get the error, others have no problems, and some get a blank screen when clicking the button.

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by theVKC** [comment] 2015-02-24 21:51
OK, good to know. Sorry @lpshanley, I’m going to regress the version back to the original. Feel free to resubmit after working the kinks out. Let me know if you have any questions. I usually find it helpful to test these by building a new redirect that points to my fork, and getting it perfect there before pull requesting.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Closed** 2015-02-24 22:03 UTC
