### ISSUE TITLE
NOTES - APPROVED PROGRAMS bug when more than one cash approval exists

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1319] opened 2015-10-28 22:57 UTC
Hennepin county user closed DWP, then opened MFIP. Since DWP was present, cdate was getting a TYPE MISMATCH error, and the script would not read any of the MFIP information. Be nice if this script could read that, especially for those DWP cases that many switch to MFIP. I could also see this coming up with CASH I/CASH II conversions for adult cash.

**Comment by theVKC** [comment] 2015-10-29 16:12
Do you want to take it, @IlseFerris?

**Comment by theVKC** [comment] 2015-10-29 16:12
(Also, I'm calling it a bug since it's throwing a type mismatch error)

**Comment by theVKC** [comment] 2015-11-02 15:32
This is a duplicate of #1262.

**Closed by theVKC** 2015-11-02 15:32 UTC
Labels: bug, duplicate, help wanted, NOTES scripts
