### ISSUE TITLE
Transfer Case

### ISSUE THREAD

**Issue by KateiMartini** [MN-Script-Team/DHS-MAXIS-Scripts#2438] opened 2016-07-20 14:18 UTC
When xfering a case within the agency, it seems as though the script is creating the spec/memo before the case is xfered.  Which is causing the spec/memo to list the current workers name and number, instead of the new workers information.

**Comment by CDPotter** [comment] 2016-07-20 15:14
It should be grabbing the user info from rept/user. Is the an error that is currently happening?

**Comment by KateiMartini** [comment] 2016-07-20 16:56
There is no error message.  It just doesn't seem to be pulling the correct workers information.

**Comment by CDPotter** [comment] 2016-07-20 19:50
Due to privileged cases any memo-ing and case noting must be done before the transfer. As such the old worker's name will still be on the signature of the memo. 

There's not really a good way around this aside from including the new worker's information in the body of the memo.

**Comment by theVKC** [comment] 2016-07-21 19:16
@CDPotter does it do this on privileged and non-privileged alike?

**Comment by CDPotter** [comment] 2016-07-21 19:18
Correct, it will always fill the body of the message with new worker's information.

**Comment by theVKC** [comment] 2016-07-21 19:41
Which checkbox specifically? I'm glancing through but don't see it. Just curious: wondering if we should include logic for privileged cases.

**Comment by CDPotter** [comment] 2016-07-21 20:31
Line 121, spec_memo_withincty_check .

The problem with having special handling with privileged cases is we generally don't know they're privileged until they are transferred. Unless I'm unaware of a way to tell.

**Comment by theVKC** [comment] 2016-07-21 22:38
What if we had a checkbox to indicate it's privileged?

**Comment by CDPotter** [comment] 2016-07-26 19:14
I often never knew if any of my cases were privileged beforehand. Does anyone else have a feel for if workers know if their cases are privileged or not?

**Comment by IlseFerris** [comment] 2016-08-08 13:53
Workers generally do not know the cases are privileged.

**Comment by CDPotter** [comment] 2016-08-08 14:52
In looking at this with Casey it appears the problem is the new workers name is pulled from the Alias section on rept/user. Washington County does not use Aliases for their users as such the new users name isn't being entered. 

The thought is if we don't find the alias we read the line above (which contains the full name of the worker) and use that name. This gets a bit tricky for case banking situations.

Can people with case banking let me know what their worker names and aliases look like?

**Comment by IlseFerris** [comment] 2016-08-08 15:00
At Hennepin the name appears as the team name. The alias is blank.

**Comment by KateiMartini** [comment] 2016-08-08 16:20
[Priv Case.zip](https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/files/407241/Priv.Case.zip)

**Comment by CDPotter** [comment] 2016-08-08 17:54
@KateiMartini showed me that we are able to navigate in a privileged case after transferring it as long as you do not back out of the case. If you use direct navigation you can enter a spec/memo in someone else's name. 

Does it also work to navigate straight to case/note?

@KateiMartini would you want to try to tackle this one?

**Comment by KateiMartini** [comment] 2016-08-08 19:07
For a privileged you would not be able to add a case note once that case has been xfered.  The case note would need to entered first, than xfer case and lastly create spec/memo.

**Comment by CDPotter** [comment] 2016-08-08 20:09
@KateiMartini would you be interested in giving this a shot? You'd probably be one of our best bets for testing it.

**Comment by CDPotter** [comment] 2016-08-10 13:39
Turns out DHS does not use aliases either so I think I'll try to work on this one today.

**Comment by CDPotter** [comment] 2016-08-10 14:14
So my solution for this is going to be if we are unable to find an alias when looking up the new worker we will use their worker name. This name goes out on all of the notices anyway. However the on the bottom of the memo seems to be limited to 20 characters (discovered by checking stearns, they are listed as Stearns Family Finan on their memos). As such I think including the full name on the memo to the client will be the best option. Here is how it would read:

Your case has been transferred. Your new worker/agency is:

   Charles D Potter
   TSQS
  MN Department of Human Services
  444 Lafayette Road
  St. Paul       55155
  651 431 4115

If you have any questions or to send in requested proofs, please direct all communications to the worker or agency listed above. 

So the only thing that's changing is we will no longer have  a blank name on the body of the memo. I feel like this is a better solution because names can be cut off if they are too long for the signature of the memo. This way the client's will get their new workers full contact information every time. 

If anyone has any objections to this please speak now. This will not affect any workers who have aliases on rept/user as the script will still find the alias and use that instead.  I will be pulling it in by the end of the week to test and then it will hit release at the end of the month.

**Closed** 2016-08-12 19:17 UTC
Labels: Category: ACTIONS, question
