### ISSUE TITLE
Enhancement request to Bulk script -> Bulk lists -> LTC-GRH-List Gen

### ISSUE THREAD

**Issue by x107208** [MN-Script-Team/DHS-MAXIS-Scripts#2834] opened 2017-01-11 14:56 UTC
Is there anyway you could add the Social worker name (from the SWKR panel) to this report?

**Comment by IlseFerris** [comment] 2017-01-11 15:28
We can certainly add this. I think if we do, the script should be customized for users to select which information they want to input into the Excel spreadsheet. It's starting to be a lot of information, and some workers might not need all of the information. It would speed up the script run time for users not selecting all options. 

Thoughts?

**Comment by x107208** [comment] 2017-01-11 15:30
I thinks options are always wonderful!  Fabulous idea!
And thank you for such a quick response time!


Thank you,

Chris Schneider
Financial Assistance Program Coordinator
Blue Earth County Human Services
PO Box 3526
Mankato MN 56002

Phone 507-304-4126
Fax 507-304-4336

**Comment by IlseFerris** [comment] 2017-01-11 15:33
Awwww shucks...

I supposed I better take this issue then. @CDPotter, Assign to me. Not only because of the flattery, but this is the 1st BULK script we ever had, and I always like working on it.

**Comment by x107208** [comment] 2017-01-11 15:35
Thank you so very much!!!! ☺

**Comment by RoberT-1000** [comment] 2017-01-11 18:39
@x107208 you can also get that data from Web-I if you have any users with access. The social worker information is a data point currently supported in the Maxis Current Data Model.

**Comment by x107208** [comment] 2017-01-12 14:05
Thank you!

I do have access to Web-I but am not very very new to it .
Do you know if I can set up a report to include all clients in facilities (or even break it down to types of facilities, for example type 41), all those on waivers and include social worker information?

Thank you so very much for you time and knowledge, it is appreciated!!
Chris ☺

**Comment by RoberT-1000** [comment] 2017-01-12 15:26
@x107208 email me at robert.kalb@co.anoka.mn.us

**Comment by CDPotter** [comment] 2017-01-20 20:22
One last pull to test @MN-Script-Team/maxis-scriptwriters

**Comment by IlseFerris** [comment] 2017-01-20 20:57
Confirmed, working in master

**Comment by courtrightd** [comment] 2017-01-20 21:01
I second that confirmation.

**Comment by C-Love** [comment] 2017-01-20 22:01
Thirded... Is that how you say that?

**Closed** 2017-01-20 22:04 UTC
Labels: enhancement
