### ISSUE TITLE
DAIL scrubber bug

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#1173] opened 2015-09-30 16:20 UTC
On CS REPORTED: NEW EMPLOYER FOR CAREGIVER REF NBR: 01 DAIL msgs the scrubber is creating the new JOBS panel but then gets stuck and is unable to finish it's other processes.

**Comment by theVKC** [comment] 2015-09-30 16:39
Why am I thinking @CDPotter or @RobertFewins-Kalb worked on this one?

**Comment by CDPotter** [comment] 2015-09-30 16:47
@RobertFewins-Kalb says he fixed it recently. Should be in all live branches

**Comment by StormageddonDLOA** [comment] 2015-09-30 17:15
I tried it just before I posted the issue and it wasn’t working then.

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842

**Comment by theVKC** [comment] 2015-09-30 17:52
How many cases did you try it on, @StormageddonDLOA? Could it be case-specific?

**Comment by StormageddonDLOA** [comment] 2015-09-30 17:53
Just one but I tried it twice on that one case.

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842

**Comment by RobertFewins-Kalb** [comment] 2015-09-30 17:54
Could you email me the case number?

robert.kalb@co.anoka.mn.us

**Comment by theVKC** [comment] 2015-09-30 17:55
Before reporting a bug, we should confirm that it's happening on multiple cases. Sometimes, circumstances in MAXIS can cause NAT errors and the like (especially from the DAIL for some reason). I'll leave it open for a bit while we investigate, but can you try this on multiple case numbers?

Also, @RobertFewins-Kalb, as reported to me by @MelissaFox-Stearns, Stearns uses a different version of BlueZone than much of the state. That's worth looking into as well, I know it's caused some heartburn on some other issues.

**Comment by StormageddonDLOA** [comment] 2015-09-30 17:55
1897406

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842

**Comment by theVKC** [comment] 2015-09-30 17:56
@StormageddonDLOA comment deleted. _Please do NOT post case numbers on GitHub or SIR._ Please send it in a separate email to Robert.

**Comment by StormageddonDLOA** [comment] 2015-09-30 18:00
Unfortunately there were only 2 cases that had that type of message and on the second case the job was already known so it never got to the point where the first case got hung up.

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842

**Comment by RobertFewins-Kalb** [comment] 2015-09-30 18:01
Hmm... 

RE: MAXIS Version... I would recommend testing it locally to try and isolate the problem.
RE: The case number that the pixies delivered to me, the DAIL message has been deleted. I cannot test.

I have no idea. I tested this up and down and it was working. The bug was originally reported by several workers, who have all since confirmed the script is working, in Anoka, at least.

**Comment by StormageddonDLOA** [comment] 2015-09-30 18:02
Perhaps it’s just an isolated incident.

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842

**Comment by RobertFewins-Kalb** [comment] 2015-09-30 18:02
Send out a message to your agency asking for case numbers. Try to test it on another worker's DAIL.

**Comment by theVKC** [comment] 2015-09-30 18:04
@StormageddonDLOA, since you reported this bug, you can close it if you wish. If you'd like to leave it open while you confirm details, that's fine too. Whatever works!

**Comment by StormageddonDLOA** [comment] 2015-09-30 18:26
Working on an overpayment right now but will try to find some case numbers to test right afterwards.

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842

**Comment by StormageddonDLOA** [comment] 2015-09-30 19:14
I found another case that did the exact same thing as I ran into earlier. I’ll forward the case number to Robert.

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842

**Comment by RobertFewins-Kalb** [comment] 2015-09-30 19:27
I think I see what might be causing the problem. Weird that nobody here reported it after the fix. When the script is back on SELF, doing nothing, it's stuck in a do-loop trying to get back to DAIL, which it's never going to do, because of navigate_to_MAXIS_screen.

I am going to go through this script and update the way it runs. This has some...let's say...legacy code in it.

Mea cupla, again, everyone.

**Comment by RobertFewins-Kalb** [comment] 2015-09-30 19:32
I need someone to test this fix. Volunteers? @StormageddonDLOA ?

**Comment by StormageddonDLOA** [comment] 2015-09-30 19:33
Sure I’ll try it again.

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842

**Comment by RobertFewins-Kalb** [comment] 2015-09-30 19:38
The code is located here.

https://raw.githubusercontent.com/RobertFewins-Kalb/Anoka-Specific-Scripts/master/CS%20NEW%20JOB%20REPORTED.vbs

Just copy/paste it into BSZH.exe and run it like a stand alone script using Blue Zone. You will have to run it from the original DAIL message. Call me if you have questions 612-352-6895.

God speed.

**Comment by StormageddonDLOA** [comment] 2015-09-30 19:46
It worked. ☺

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842

**Comment by RobertFewins-Kalb** [comment] 2015-09-30 19:47
![image](https://cloud.githubusercontent.com/assets/7842016/10204572/318c9c66-6782-11e5-8d2a-c3931805175b.png)

**Comment by theVKC** [comment] 2015-09-30 20:32
Reopening issue, as I am still pulling the fix in. @StormageddonDLOA, if a pull request closes the issue, I like to chain those. If we decide an issue isn't an issue, you can close this. You didn't know, so it's OK.

**Closed** 2015-09-30 20:33 UTC
Labels: bug, DAIL scrubber scripts, question
