### ISSUE TITLE
GA/SNAP FIATER

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#734] opened 2015-06-18 20:44 UTC
Also from Neil Trembley at Hennepin County
FIAT GA/SNAP.  My most repetitive task that I do is FIATing GA/SNAP.  Time consuming rote work.  Almost always the same; is always the same when I am changing (like updating DISA with an extension of the DISA end date—something we do all the time) and then producing DAIL action items to approve new GA/SNAP results.  It would be a great boon to humankind if this could be automated.  

@LaLarson were you working on something like this?

**Comment by CDPotter** [comment] 2015-06-18 20:55
So something to grab the GA results and put them into the SNAP budget? or FIATING both GA and SNAP?

**Comment by IlseFerris** [comment] 2015-06-18 20:59
For now just FIAT the GA into the SNAP budget

**Comment by LaLarson** [comment] 2015-06-18 21:05
I do have something of this nature that I was working on... I'm away right now, but I'll be in tomorrow... Let me check, and get back to you tomorrow morning? I know it was like 80% done?

Sent from my iPhone

On Jun 18, 2015, at 3:44 PM, Ilse Ferris <notifications@github.com<mailto:notifications@github.com>> wrote:


Also from Neil Trembley at Hennepin County
FIAT GA/SNAP. My most repetitive task that I do is FIATing GA/SNAP. Time consuming rote work. Almost always the same; is always the same when I am changing (like updating DISA with an extension of the DISA end date—something we do all the time) and then producing DAIL action items to approve new GA/SNAP results. It would be a great boon to humankind if this could be automated.

@LaLarson<https://github.com/LaLarson> were you working on something like this?

—
Reply to this email directly or view it on GitHub<https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/734>.

NOTICE: This e-mail and any files transmitted with it are intended only for the use and viewing of the individual or entity to which they are addressed. If you are not the intended recipient, please immediately notify the sender of the transmission error and then promptly delete this message from your computer system. Please be advised that e-mail correspondence to and from Goodhue County may be public data subject to the Minnesota Data Practices Act and may be disclosed to third parties.

**Comment by IlseFerris** [comment] 2015-06-19 13:16
Awesome!  I thought that was the case.

**Comment by theVKC** [comment] 2015-06-19 13:59
This is a duplicate of #393. Yo @IlseFerris... remember to search for existing issues before creating new ones.

**Closed** 2015-06-19 13:59 UTC
Labels: duplicate

**Comment by IlseFerris** [comment] 2015-06-19 14:21
Oh shoot, didn't think this one was on there.  Sorry about that one (wah wah)
