### ISSUE TITLE
MASTER CSR bugs: Do...loop logic and double quotes issue

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1109] opened 2015-09-18 21:09 UTC
Anyone on MASTER branch unable to open CSR?

**Comment by CDPotter** [comment] 2015-09-18 21:23
Looks like one of the new text fields had Quotes in it and didn't have the double quotes EX
"This is the example ""Example text"" this is the end of sentence". It also looks like at some point the if statement around the check FS elig info was removed? The checkbox never gets used anywhere else. Should we revert this one or should I readd the IF logic and correct the Quote issue?

**Comment by theVKC** [comment] 2015-09-22 16:47
Is this happening for anyone else while working in MASTER branch? @RobertFewins-Kalb, @IlseFerris, @mldietz, @courtrightd?

Also, friendly reminder: bugs that are just in MASTER are NOT critical, because they only affect scriptwriters.

**Comment by RobertFewins-Kalb** [comment] 2015-09-22 16:53
Whoa!

![image](https://cloud.githubusercontent.com/assets/7842016/10025173/8224acc6-6120-11e5-8d6d-f3a36aa5e616.png)

**Comment by theVKC** [comment] 2015-09-22 16:57
Not sure what I'm looking at. Could this tie in to #1002? If so, @RobertFewins-Kalb, could you do the honor of splitting this into two dialogs, possibly with dynamic content? I'd want a fix to come out before tomorrow-ish.

**Comment by mldietz** [comment] 2015-09-22 16:59
I can't open the CSR script at all.  I get an error msg.  Charles looked at what I was getting last week and said he would look into it.

**Comment by theVKC** [comment] 2015-09-22 17:01
This sounds like it's a separate issue from #1002, but one talented scriptwriter could kill both birds with one code-stone. I'm hoping @RobertFewins-Kalb could do me the honor, as I turn into a pumpkin (log off for the day) in only a half hour.

**Comment by IlseFerris** [comment] 2015-09-22 17:07
Also confirming the error on my end.

**Comment by RobertFewins-Kalb** [comment] 2015-09-22 17:44
On it. This will get me out of Compass Appointments!!

**Comment by RobertFewins-Kalb** [comment] 2015-09-22 18:19
I have fixed the syntax issues, but I am not seeing a logic way of dividing the dialog into 2. The problem is that 24 of the objects in the dialog are navigation buttons (to be fair, I think we can get rid of the CASH navigation button).

**Comment by RobertFewins-Kalb** [comment] 2015-09-22 18:20
(merged conversation with #1002 )

**Closed** 2015-09-23 19:28 UTC
Labels: bug, NOTES scripts
