### ISSUE TITLE
QUESTION: Scripts updated to work with the modified new hire messages?

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#2966] opened 2017-09-07 14:57 UTC
I'm not sure how or who to even submit this question to since this repository probably isn't being actively monitored. One of my workers has a question so I thought I'd put it on here just in case someone sees it :) She is wondering if scripts will be updated to work with the modified new hire messages? If someone sees this and is able to respond, great. If not, it's a-ok.

**Comment by Farleight** [comment] 2017-09-07 16:49
This issue is being discussed, so have no fear. It's a layered issue. I think there will be a fix to make the DAIL scrubber work, in the same way it used to work, very soon. It will probably take more time to address the new actions we are supposed to take to clear them though, if that is something that can be handled at all... I am just a lowly peon though; my main goal here is to let you know the problem is under review.

**Comment by ALJ10** [comment] 2017-09-07 17:55
I wasn’t expecting an answer so I appreciate your quick response to this!

I will let the worker know that it’s being reviewed and leave it at that. Thank you for the update on it!

Amanda Jensen
Technology Coordinator/Onbase OCSA_OCWA_OCAWA Certified
Crow Wing County Community Services
P.O. Box 686, 204 Laurel Street
Brainerd, MN 56401
Office:  (218) 824-1235
Fax:     (218) 824-1141
www.crowwing.us<http://www.crowwing.us/>
[http://mn-crowwingcounty.civicplus.com/DocumentCenter/View/5692]
Our Vision: Being Minnesota’s favorite place.
Our Mission: Serve well. Deliver value. Drive results.
Our Values: Be responsible. Treat people right. Build a better future.

Let me know how I am doing. Take a moment to fill out this survey by "Clicking Here".<https://www.surveymonkey.com/r/CommunityServiceLeadership>

**Comment by KLeflay** [comment] 2017-09-08 17:45
We have a new staff person who is interested in potential script writing, how do I get him connected to the group?  Thanks, Kay Leflay, Scott County

**Comment by Farleight** [comment] 2017-09-08 18:04
Simply submit an annual $70.00 licensing fee to my account in the Caymans. Actually, I do not know the process at this time. There used to be a multi-day class... and then there was a shortened class... and then there was no longer any supervision whatsoever. Basically, it's Lord of the Flies here now. 

Does he have experience in any kind of scripting language already, or would he be starting from scratch? Either way, I'll try to track down an answer for you (if no one else fields it in the meantime). You or he can email me directly if you wish. Then we can keep the conversation offline to avoid cluttering up this New Hire issue, and to make it easier for me to convince you about the licensing fee without having too many witnesses.

Travis.Farleigh@co.carlton.mn.us

**Comment by x143626** [comment] 2017-10-04 14:03
Has any more been done regarding this issue?  I believe our agency is also experiencing the same problem. Dail scrubber worked last month, but is not working this month for State MN new hire dails.  Error msg for all new hire dails for State MN jobs reads as follows:
You are not on a supported DAIL message. The script will now stop.
The message reads: (client SSN Number) NEW MN JOB DETAILS FOR (client name)

**Comment by Farleight** [comment] 2017-10-04 14:44
I have conferred with your friendly neighborhood script-writers and here's the general overview:

Because we have very little (meaning zero) control over the state-sponsored script database, they have created a new one, which is basically a clone of the original. In doing so, we now have complete control over the cloned version while the state one can sit there safely untouched until such time as we get supervision again... what does this mean for counties? 

In order to utilize the new "branch" you'll need to set your "Global Variables" to look in the scriptwriter collaborative repository of GitHub, rather than whatever you currently have it set to look toward (most likely Master or Release branch).

Now if you know what I'm talking about when I say all that, great! You probably understand it better than I do. If it all sounds Greek, first take it to whomever is the main script-guru in your county... if, as in my case, that's you, and you still have no clue what I'm talking about, we'll need to just talk you through things probably.

But prior to putting the cart before the horse, I will warn, this is a big change which takes the database out of the "approved" status the state can grant it, and puts it in the hands of actual humans. Your county may not agree with the decision to do this (even though it is the correct decision). If you do not have authority to make sweeping changes or the blatant disregard for rules to do it without asking, you'll probably need to run this by your IT or Admin or whoever makes these decisions in your agency.

**Comment by ALJ10** [comment] 2017-10-04 19:13
Thank you for the information! Glad to hear there are finally humans maintaining them again ☺ Can you share with us what the URL is for the cloned repository?

**Comment by C-Love** [comment] 2017-10-05 12:33
I don't think this change has been pulled in to the branch. I will pull it in today and tag this issue, that way the branch and code change will be listed here.

**Comment by Farleight** [comment] 2017-10-05 19:40
Just to keep interested parties apprised of the situation:

The branch URL is:
"https://raw.githubusercontent.com/MN-Script-Team/DHS-MAXIS-Scripts/scriptwriter_collaborative/Script Files/"

However, some of (one, for sure) the Redirect files in your local directory may need some minor tweakage too. Sorry for any delays this may cause, but we are collectively trying to figure out the best, and easiest to explain and implement, solution. Hang in there!

**Comment by Farleight** [comment] 2017-10-05 19:41
That came out looking weird... just FYI, the whole thing is the URL... not just the blue.

**Comment by C-Love** [comment] 2018-02-21 18:14
This will update 2 issues:
1. addressing the coordinates move that is referenced in the actual DAIL Scrubber file
2. Addressing the process change in the NDNH New Hire DAILS.

**Comment by MiKaylaH22** [comment] 2018-02-27 16:21
We have a fix for this. We added the handling for NDNH matches and they have been clearing correctly.

**Closed** 2018-03-02 18:57 UTC
Labels: CRITICAL, Category: DAIL scrubber, Status: help wanted, Type: bug
