### ISSUE TITLE
The CS DISREGARD WCOM should be a stand alone script 

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1277] opened 2015-10-15 22:39 UTC
So that workers can tell the script which months to be putting the WCOM into the notice...for approvals of multiple months.

We have a stand alone script and can submit the pull.

**Comment by theVKC** [comment] 2015-10-19 13:47
Is this on Approved Progs now? If so, are you proposing it be removed? Chain run? Whacha thinking @RobertFewins-Kalb?

**Comment by RobertFewins-Kalb** [comment] 2015-10-19 13:55
I wasn't thinking about chain loading, but just having a script that will dump the verbiage on the notice should someone forget to hit the checkbox, or should someone have notices from multiple months to add the WCOM.

**Comment by theVKC** [comment] 2015-10-28 20:04
Would chain loading be better? You'd get to change one place and it'd change both? Gather better stats that way? Asking for a friend...

**Comment by Y-Lor-Y** [comment] 2015-10-28 20:26
I can see that worker may forget to click that checkbox...and wants to run that sole part of the wcom for the CS Disregard.  Chaining is good, but have that chain from another script, like processing a HRF and you want to chain it to the CS disregard...same with Approved program, but the question is, should the worker run approved program x2 to just get CS disregard on the WCOM.  I can see where Robert is coming from and having that as stand alone for the action it required w/o having to run other type of scripts to just get what I want out of it can be a good idea, too.    *two cents*

**Comment by theVKC** [comment] 2015-10-28 20:33
Step 1. Make a separate script for it.
Step 2. Build functionality to allow Approved Programs to run the separate script.
Step 3. Collect statistics on both functions using the same metric.

**Comment by CDPotter** [comment] 2015-10-29 16:02
Question, will we need the WCOM anymore? It reads:

Starting October 1, 2015 a new law begins that allows us to not count some of the child support you get when determining your monthly MFIP/DWP benefit amount: ... Because of this change, you may see an increase in your benefit amount.

Seems like it's really only needed to inform people of the change when we started using it.

**Comment by theVKC** [comment] 2015-10-29 16:14
No, I think we still need it in order to clarify that it's a break from the past. But I'm no expert, anyone want to reach out to an MFIP mentor? I'm wondering if @Y-Lor-Y or @C-Love would want to handle that for me, what-with-their connections and better understanding of these nuances. If not, I'll give it a whirl.

**Comment by Y-Lor-Y** [comment] 2015-10-29 16:40
I'm asking my connections...

**Comment by theVKC** [comment] 2015-10-29 17:15
Thanks @Y-Lor-Y!

**Comment by Y-Lor-Y** [comment] 2015-11-02 22:14
Here is my response from DHS - BA:
It is recommended that whenever the worker has fiatted the exclusion into the MFIP or DWP budget calculation, the resulting notice should include the worker comment.  This applies to all approvals done beginning in 10/15 and continuing until background has been updated to include the exclusion.  Once the system is automated, the worker comment will not be needed; notices will include reference to the exclusion.

So the answer to the question would be that yes, the SPEC/WCOM notice on this script is required until it is automated...as to when exactly, we don't know at this point.  @theVKC  @CDPotter

**Comment by RobertFewins-Kalb** [comment] 2015-11-02 22:16
#AdNauseam

**Comment by RobertFewins-Kalb** [comment] 2015-11-02 22:18
@Y-Lor-Y , thank you for looking into that.

**Comment by theVKC** [comment] 2015-11-04 17:23
@RobertFewins-Kalb, do you still want this script?

**Comment by RobertFewins-Kalb** [comment] 2015-11-05 14:27
We have the script, but we're in a script freeze. Shall I upload or withhold?

**Comment by theVKC** [comment] 2015-11-05 14:32
Monday would be OK (after the beta freeze). The big script freeze relates to new scripts _not already on the issue list in GitHub._

**Comment by RobertFewins-Kalb** [comment] 2015-11-05 14:33
Okum dokes

**Comment by theVKC** [comment] 2015-11-05 14:41
Wonderful. Thanks @RobertFewins-Kalb!

**Comment by Y-Lor-Y** [comment] 2015-11-05 16:26
Heard more from DHS on a related by different situation, cause I've encountered cases where notices are not being generated because due to the disregard fiated, it resulted in the same grants (no change) (though different CS amount rec'vd) for next month.  When MFIP approved after Fiating...no notice is generated.  Thus worker cannot comment on the SPEC/WCOM.  There is already a safety logic in place informing worker when there is no notice generated in SPEC/WCOM.  Just thought I share this with you all.  Which in away make sense in regard to the notice not being generated.  @RobertFewins-Kalb  @theVKC  @CDPotter

**Comment by theVKC** [comment] 2015-11-05 16:28
Hmmm. MFIP approved after FIATing = no notice at all? Why doesn't that sound right to me?

**Comment by Y-Lor-Y** [comment] 2015-11-05 16:29
If it's a 'No Change' from what was already approved previous month.

**Comment by theVKC** [comment] 2015-11-05 16:34
But approving that "no change" generates NO notice? Why does that seem weird to me?

**Comment by Y-Lor-Y** [comment] 2015-11-05 16:38
DHS-BA confirmed that that's an okay thing.  I did a PF11 requesting if this is a system issue or a long delay on the system.  The response I got back was, that is how it suppose to be.  /shrugs

**Comment by RobertFewins-Kalb** [comment] 2015-11-05 16:41
We've noticed the same thing. Not sure why that's the case, shoulder shrug appears to be the actual answer.

**Comment by theVKC** [comment] 2015-11-05 16:46
If I were a client, I'd want to know about my benefits being approved at no change. I come from the SNAP world, that doesn't fly in our place.

**Comment by RobertFewins-Kalb** [comment] 2015-11-05 16:51
I wonder if this only applies to cases with cash only? Don't we audit the food portion the same as we do SNAP? Could it be that cases that are cash only do not get a notice when there is no change to the benefit?

**Comment by RobertFewins-Kalb** [comment] 2015-11-05 16:51
So many questions, so few Jesse Venturas.

**Comment by Y-Lor-Y** [comment] 2015-11-05 16:55
It is true for MFIP that the food portion gets audit the same as SNAP, however, due to the SNAP waiver in MN only, not sure how that affects system vs. policy.  This seems like a deja vu topic that was long forgotten and shut out of my mind for a reason.

**Comment by theVKC** [comment] 2015-11-05 17:16
Uh oh... @ruthmaloney, have you ever heard of this? I figure since we review MFIP-food this might intersect us (thanks for pointing out that monkey-wrench @RobertFewins-Kalb)

**Comment by theVKC** [comment] 2016-01-15 19:43
Can I get a status update @RobertFewins-Kalb? If no progress has been made I'll close the issue.

**Comment by RobertFewins-Kalb** [comment] 2016-01-15 19:44
I'll add it

**Closed** 2016-01-15 19:58 UTC
Labels: MEMOS scripts, new script idea
