### ISSUE TITLE
NOTES - Approved Program & MFIP/DWP Sanction

### ISSUE THREAD

**Issue by Y-Lor-Y** [MN-Script-Team/DHS-MAXIS-Scripts#1381] opened 2015-11-10 19:42 UTC
A worker ran both of these scripts one after another, and could not add the WCOM information for both situations on the same WCOM notice - and had to manually enter it in.  Even doing that was challenging due to space allowed.  She could run either WCOM notice, but then when running the other script asking it to write onto WCOM, it would respond saying that the script is not able to update the WCOM.  

I'm thinking that maybe we should removed from the MFIP/DWP script where it would write onto WCOM and add this part as an additional check item for the approved program.  OR, Add an additional check box to the MFIP/DWP script to note a MEMO instead if client has other program using the WCOM - which in turn would then require a more detailed wording MEMO of the sanction.

I guess I'm asking to see if there is/are any good solution to the above?

**Comment by theVKC** [comment] 2015-11-10 21:05
I'm going to mark this as "question" because I think it warrants discussion... anyone at @MN-Script-Team/county-agency-scriptwriters have an opinion?

**Comment by StormageddonDLOA** [comment] 2015-11-10 21:37
By looking at the MFIP Sanction - DWP Disqualification script I'd think it should be possible to remove the check box to write a SPEC/WCOM and move it to the approved programs script (and perhaps add a popup message box reminder to add WCOM info from the approved progs script) however if there are space issues when trying to do both WCOM messages on the approved progs script one or both parts of the WCOM added will probably need to be tweaked.

**Comment by theVKC** [comment] 2015-11-10 21:44
Should we consider creating a stand-alone script for the WCOM and chain-loading them?

**Comment by IlseFerris** [comment] 2015-11-17 13:21
Worker at Hennepin also reported the WCOM on MFIP sanction not working. It seems that a lot of the information that needs to be put into WCOM is mandatory. I think we should consider building it in instead of check boxes.

**Comment by theVKC** [comment] 2015-11-17 14:14
Couldn't we add it into both fields with chain loading though? How hard is another dialog when it pops up for you after checking a box and pressing OK? That way, it's one script to edit/update/improve each time this process changes.

**Comment by theVKC** [comment] 2016-01-15 19:54
Closing this. I'm thinking it's a duplicate of #1262 which is assigned to @C-Love for a fix.

**Comment by theVKC** [comment] 2016-01-15 19:55
Maybe it's a duplicate? I don't know. Thinking @Y-Lor-Y or @C-Love should enlighten me. :)

**Closed by theVKC** 2016-01-15 19:54 UTC
Labels: NOTES scripts, question

**Comment by Y-Lor-Y** [comment] 2016-01-16 06:05
What was assigned to Casey was to fix the Approved program.

Issue on #1381 is for current situation when a worker have to run both
scripts - the approved program with the spec/memo of the CS disregard note &
to run the sanction script - to impose sanction, but also want/need to note the wcom
informing client of the sanction.

So, if what was assigned to Casey will fix the spec/wcom notation then issue #1381 is duplicate.
But I don't think that it is a duplicate, as it's two separate scripts that is running into an issue.

I hope that helps a bit.

Thanks,
Yang
________________________________________
